### ISSUE TITLE
Commit ID and refresh icon not visible

### ISSUE THREAD

**Issue by AvijeetPrasad** [mandpd/logseq-plugin-github-get#1]
Hi, 
Thanks for writing this useful plugin and on suggestions on how to use it effectively for code documentation. I was able to set up the GitHub authentication key based on the `README` instructions. I am also able to obtain a copy of the file from GitHub after running the `Get GitHub File` command. But I am not getting the `commit ID` and the `refresh` button options. Please see the attached screenshot for reference.

I am on Logseq `0.6.6` on `macOS 12.2.1`. Can you please have a look and let me know if I am missing something? Looking forward to your suggestions.

![Screenshot 2022-04-28 at 14 33 13](https://user-images.githubusercontent.com/45669486/165752882-7fb8bfe0-1333-41b0-8fb0-748de59e4fef.jpg)

**Comment by AvijeetPrasad** [comment]
Hi, 

After restarting uninstalling and reinstalling the plugin and also restarting Logseq, now the renderer for commit ID is working fine. So no issues now :)

**Comment by mandpd** [comment]
Hi,

glad you like the plugin! Not sure what might have happened first time round, but I'm glad it cleared itself after the reinstall and restart. Let me know if you see the same issue after an update. I've noticed that Logseq can need a restart to update a plugin, but you shouldn't need to uninstall and reinstall the plugin.
